#!/bin/sh

BSPJOB=4
BSPROOT=`pwd`
BSPTOOLS=${BSPROOT}/tools/o
BSPROOTFS=${BSPROOT}/rootfs
BSPINSTALL=${BSPROOT}/miner  # change to /usr/local/bin if you like!
PATH=${BSPTOOLS}/o/bin:${PATH}

export BSPJOB BSPROOT BSPTOOLS BSPROOTFS BSPINSTALL PATH

# tool selection
export TOOLS_ENABLE_OBJCONV=y
export TOOLS_ENABLE_FASM=y
export TOOLS_ENABLE_CMAKE=y
